# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('discounts', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='couponcategory',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scope', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='couponproduct',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scope', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='couponproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='discountcondition',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='customers.customer'),
        ),
    ]
