# Generated by Django 6.0.2 on 2026-03-26 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0002_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountusage',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_usages', to='sales.sale'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['hub_id', 'is_active'], name='discounts_p_hub_id_692c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['valid_from', 'valid_until'], name='discounts_p_valid_f_735ed8_idx'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.promotion'),
        ),
        migrations.AddField(
            model_name='discountcondition',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='discounts.promotion'),
        ),
        migrations.AddField(
            model_name='promotioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='promotioncategory',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scope', to='discounts.promotion'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='promotionproduct',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scope', to='discounts.promotion'),
        ),
        migrations.AlterUniqueTogether(
            name='couponcategory',
            unique_together={('coupon', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='couponproduct',
            unique_together={('coupon', 'product')},
        ),
        migrations.AddIndex(
            model_name='discountusage',
            index=models.Index(fields=['used_at'], name='discounts_u_used_at_8f05da_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='promotioncategory',
            unique_together={('promotion', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='promotionproduct',
            unique_together={('promotion', 'product')},
        ),
    ]
